# Generated by Django 5.1.3 on 2024-11-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('CustomerNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SalesOrg', models.CharField(max_length=4)),
                ('AccountGroup', models.CharField(max_length=4)),
                ('CustomerName1', models.CharField(max_length=35)),
                ('CustomerName2', models.CharField(blank=True, max_length=35, null=True)),
                ('SearchTerm', models.CharField(max_length=20)),
                ('HouseStreetName', models.CharField(max_length=60)),
                ('City', models.CharField(max_length=35)),
                ('Country', models.CharField(max_length=3)),
                ('CustomerClass', models.CharField(max_length=2)),
                ('IndCode1', models.CharField(max_length=4)),
                ('KeyAccount', models.BooleanField(default=False)),
                ('SalesGroup', models.CharField(max_length=3)),
                ('CustPriceProc', models.CharField(max_length=2)),
                ('TermOfPayment', models.CharField(max_length=4)),
                ('Incoterms', models.CharField(max_length=3)),
                ('IncotermsPort', models.CharField(max_length=28)),
                ('TradingCurrency', models.CharField(max_length=5)),
                ('CustomerBlocked', models.BooleanField(default=False)),
                ('CustomerDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('MaterialNumber', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('Plant', models.CharField(max_length=4)),
                ('MaterialDescription', models.CharField(max_length=40)),
                ('CrossPlantStatus', models.CharField(max_length=2)),
                ('DrawingNumber', models.CharField(max_length=30)),
                ('FourDigitDescription', models.CharField(max_length=40)),
                ('BasicMaterial', models.CharField(max_length=30)),
                ('BasicMatDescription', models.CharField(max_length=40)),
                ('MachineType', models.CharField(max_length=30)),
                ('ProductGroup', models.CharField(max_length=30)),
                ('ProductType', models.CharField(max_length=30)),
                ('LifeCycleFlag', models.CharField(max_length=2)),
                ('PlantOldMaterialNumber', models.CharField(max_length=18)),
                ('ProductHierarchy', models.CharField(max_length=18)),
                ('UnitOfMeasure', models.CharField(max_length=3)),
            ],
        ),
    ]
