# Generated by Django 4.2.7 on 2024-11-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('CurrencyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('CurrencyExchangeID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ExchangeFactor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('FromCurrencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='finance.currency')),
                ('ToCurrencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='finance.currency')),
            ],
        ),
    ]
