# Generated by Django 5.0.9 on 2024-11-17 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CurrencyID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('CurrencyName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('CurrencyExchangeID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ExchangeFactor', models.DecimalField(decimal_places=4, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('EffectiveDate', models.DateField(blank=True, null=True)),
                ('FromCurrencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_exchanges', to='finance.currency')),
                ('ToCurrencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_exchanges', to='finance.currency')),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'verbose_name_plural': 'Currency Exchange Rates',
                'unique_together': {('FromCurrencyID', 'ToCurrencyID')},
            },
        ),
    ]
