# Generated by Django 4.2.7 on 2024-11-13 00:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='currencyexchange',
            options={'verbose_name': 'Currency Exchange Rate', 'verbose_name_plural': 'Currency Exchange Rates'},
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='EffectiveDate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='CurrencyName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='ExchangeFactor',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='FromCurrencyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_exchanges', to='finance.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='ToCurrencyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_exchanges', to='finance.currency'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchange',
            unique_together={('FromCurrencyID', 'ToCurrencyID', 'EffectiveDate')},
        ),
    ]
