# Generated by Django 4.2.7 on 2024-11-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='QStatusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quotation.quotationstatus'),
        ),
        migrations.AlterField(
            model_name='quotationdetails',
            name='SalesOrganization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.salesorganization'),
        ),
    ]
