# Generated by Django 4.2.7 on 2024-11-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-CreationDate', 'QuotationNo'], 'verbose_name': 'Quotation', 'verbose_name_plural': 'Quotations'},
        ),
    ]
