# Generated by Django 4.2.7 on 2024-11-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation_created_by_quotation_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
