# Generated by Django 5.1.3 on 2024-11-17 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CountryID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Country ID')),
                ('CountryName', models.CharField(max_length=50, unique=True, verbose_name='Country Name')),
                ('CountryCode', models.CharField(max_length=3, unique=True, verbose_name='Country Code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['CountryName'],
                'indexes': [models.Index(fields=['CountryCode'], name='company_cou_Country_c8008e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CompanyID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Company ID')),
                ('CompanyName', models.CharField(max_length=50, unique=True, verbose_name='Company Name')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('CountryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['CompanyName'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrganization',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('SalesOrganizationID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Sales Organization ID')),
                ('SalesOrganizationName', models.CharField(max_length=50, unique=True, verbose_name='Sales Organization Name')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_organizations', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Sales Organization',
                'verbose_name_plural': 'Sales Organizations',
                'ordering': ['SalesOrganizationName'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('AccountGroupID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account Group ID')),
                ('AccountGroupName', models.CharField(max_length=50, unique=True, verbose_name='Account Group Name')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('SalesOrganizationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='company.salesorganization', verbose_name='Sales Organization')),
            ],
            options={
                'verbose_name': 'Account Group',
                'verbose_name_plural': 'Account Groups',
                'ordering': ['AccountGroupName'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['IsActive'], name='company_com_IsActiv_456c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorganization',
            index=models.Index(fields=['IsActive'], name='company_sal_IsActiv_2aabb7_idx'),
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['IsActive'], name='company_acc_IsActiv_73a316_idx'),
        ),
    ]
