# Generated by Django 4.2.7 on 2024-11-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountgroup',
            options={'verbose_name': 'Account Group', 'verbose_name_plural': 'Account Groups'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='salesorganization',
            options={'verbose_name': 'Sales Organization', 'verbose_name_plural': 'Sales Organizations'},
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='AccountGroupName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='SalesOrganizationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='company.salesorganization'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='CountryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='CountryName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorganization',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_organizations', to='company.company'),
        ),
        migrations.AlterField(
            model_name='salesorganization',
            name='SalesOrganizationName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
