# Generated by Django 5.1.3 on 2024-11-17 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountgroup',
            options={'ordering': ['AccountGroupName'], 'verbose_name': 'Account Group', 'verbose_name_plural': 'Account Groups'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['CompanyName'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['CountryName'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='salesorganization',
            options={'ordering': ['SalesOrganizationName'], 'verbose_name': 'Sales Organization', 'verbose_name_plural': 'Sales Organizations'},
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='country',
            name='CountryCode',
            field=models.CharField(default='XXX', max_length=3, unique=True, verbose_name='Country Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesorganization',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='salesorganization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesorganization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='AccountGroupID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Account Group ID'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='AccountGroupName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Account Group Name'),
        ),
        migrations.AlterField(
            model_name='accountgroup',
            name='SalesOrganizationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_groups', to='company.salesorganization', verbose_name='Sales Organization'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CountryID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='CountryID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Country ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='CountryName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='salesorganization',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_organizations', to='company.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='salesorganization',
            name='SalesOrganizationID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Sales Organization ID'),
        ),
        migrations.AlterField(
            model_name='salesorganization',
            name='SalesOrganizationName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sales Organization Name'),
        ),
        migrations.AddIndex(
            model_name='accountgroup',
            index=models.Index(fields=['IsActive'], name='company_acc_IsActiv_73a316_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['IsActive'], name='company_com_IsActiv_456c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='country',
            index=models.Index(fields=['CountryCode'], name='company_cou_Country_c8008e_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorganization',
            index=models.Index(fields=['IsActive'], name='company_sal_IsActiv_2aabb7_idx'),
        ),
    ]
